FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY cmd ./cmd
COPY internal ./internal
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/sstest ./cmd/sstest

FROM scratch
COPY --from=build /out/sstest /usr/local/bin/sstest
ENTRYPOINT ["/usr/local/bin/sstest"]
