FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/sstest ./cmd/sstest

FROM scratch
COPY --from=build /out/sstest /usr/local/bin/sstest
COPY LICENSE THIRD_PARTY_NOTICES.md /
ENTRYPOINT ["/usr/local/bin/sstest"]
