package flyskynode

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/database64128/shadowsocks-go/conn"
	"github.com/database64128/shadowsocks-go/router"
	"github.com/database64128/shadowsocks-go/service"
)

type staticIPResolver struct {
	answers map[string][][]netip.Addr
	calls   map[string]int
}

func (r *staticIPResolver) LookupNetIP(_ context.Context, network, host string) ([]netip.Addr, error) {
	if network != "ip4" {
		return nil, errors.New("unexpected resolver network")
	}
	if r.calls == nil {
		r.calls = make(map[string]int)
	}
	index := r.calls[host]
	r.calls[host]++
	sets, ok := r.answers[host]
	if !ok || len(sets) == 0 {
		return nil, errors.New("no test answer")
	}
	if index >= len(sets) {
		index = len(sets) - 1
	}
	return sets[index], nil
}

func emptyInterfaceAddrs() ([]net.Addr, error) { return nil, nil }

func newTestOutboundACL(t *testing.T, resolver ipResolver, protected ...netip.Prefix) *outboundACL {
	t.Helper()
	acl, err := newOutboundACLWithDependencies(
		"https://panel.example/api/v1",
		protected,
		resolver,
		emptyInterfaceAddrs,
	)
	if err != nil {
		t.Fatalf("newOutboundACLWithDependencies: %v", err)
	}
	return acl
}

func TestOutboundACLIPv4DefaultPolicy(t *testing.T) {
	acl := newTestOutboundACL(t, &staticIPResolver{})
	tests := []struct {
		name  string
		ip    string
		allow bool
	}{
		{name: "public DNS one", ip: "1.1.1.1", allow: true},
		{name: "public DNS two", ip: "8.8.8.8", allow: true},
		{name: "unspecified", ip: "0.0.0.0"},
		{name: "loopback", ip: "127.0.0.1"},
		{name: "private ten", ip: "10.0.0.1"},
		{name: "private one seven two", ip: "172.16.0.1"},
		{name: "private one nine two", ip: "192.168.1.1"},
		{name: "carrier NAT", ip: "100.64.0.1"},
		{name: "link local metadata", ip: "169.254.169.254"},
		{name: "carrier NAT metadata", ip: "100.100.100.200"},
		{name: "benchmark", ip: "198.18.0.1"},
		{name: "documentation one", ip: "192.0.2.1"},
		{name: "documentation two", ip: "198.51.100.1"},
		{name: "documentation three", ip: "203.0.113.1"},
		{name: "multicast", ip: "239.1.2.3"},
		{name: "reserved", ip: "240.0.0.1"},
		{name: "public IPv6 first release", ip: "2001:4860:4860::8888"},
		{name: "mapped public IPv4", ip: "::ffff:8.8.8.8"},
		{name: "mapped private IPv4", ip: "::ffff:10.0.0.1"},
		{name: "NAT64 public IPv4", ip: "64:ff9b::808:808"},
		{name: "NAT64 metadata IPv4", ip: "64:ff9b::a9fe:a9fe"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			target := conn.AddrFromIPAndPort(netip.MustParseAddr(tc.ip), 443)
			resolved, err := acl.ResolveAndAuthorize(t.Context(), target)
			if tc.allow {
				if err != nil {
					t.Fatalf("allowed target rejected: %v", err)
				}
				if len(resolved) != 1 || !resolved[0].IsIP() || resolved[0].IP() != target.IP() {
					t.Fatalf("resolved target = %v, want %v", resolved, target)
				}
				return
			}
			if !errors.Is(err, router.ErrRejected) {
				t.Fatalf("rejected target error = %v, want ErrRejected", err)
			}
		})
	}
}

func TestParseSystemDNSUpstreamsKeepsExactUsableIPv4Resolvers(t *testing.T) {
	input := strings.NewReader(`
# generated by the node provider
nameserver 100.100.101.101
nameserver 100.100.101.102
nameserver 100.100.101.101
nameserver 127.0.0.53
nameserver 169.254.169.254
nameserver 2001:4860:4860::8888
nameserver 1.1.1.1
nameserver 8.8.8.8
`)
	upstreams, err := parseSystemDNSUpstreams(input)
	if err != nil {
		t.Fatalf("parseSystemDNSUpstreams: %v", err)
	}
	want := []netip.Addr{
		netip.MustParseAddr("100.100.101.101"),
		netip.MustParseAddr("100.100.101.102"),
		netip.MustParseAddr("127.0.0.53"),
		netip.MustParseAddr("1.1.1.1"),
	}
	if fmt.Sprint(upstreams) != fmt.Sprint(want) {
		t.Fatalf("system DNS upstreams = %v, want %v", upstreams, want)
	}
}

func TestValidNodeDNSUpstreamAllowsContainerResolversButNotVirtualOrReservedTargets(t *testing.T) {
	tests := []struct {
		address string
		want    bool
	}{
		{address: "127.0.0.11", want: true},
		{address: "100.100.101.101", want: true},
		{address: "198.18.0.2", want: true},
		{address: "1.1.1.1", want: true},
		{address: "198.18.0.53", want: false},
		{address: "169.254.169.254", want: false},
		{address: "192.0.2.53", want: false},
		{address: "240.0.0.53", want: false},
		{address: "2001:4860:4860::8888", want: false},
	}
	for _, tc := range tests {
		t.Run(tc.address, func(t *testing.T) {
			if got := validNodeDNSUpstream(netip.MustParseAddr(tc.address)); got != tc.want {
				t.Fatalf("validNodeDNSUpstream(%s) = %v, want %v", tc.address, got, tc.want)
			}
		})
	}
}

func TestOutboundACLMapsOnlyVirtualDNSPortToExactSystemResolvers(t *testing.T) {
	upstreams := []netip.Addr{
		netip.MustParseAddr("100.100.101.101"),
		netip.MustParseAddr("100.100.101.102"),
	}
	acl, err := newOutboundACLWithDNSDependencies(
		"https://panel.example/api/v1",
		[]netip.Prefix{netip.MustParsePrefix("100.100.101.0/24")},
		&staticIPResolver{},
		emptyInterfaceAddrs,
		upstreams,
	)
	if err != nil {
		t.Fatalf("newOutboundACLWithDNSDependencies: %v", err)
	}

	virtual := conn.AddrFromIPAndPort(nodeDNSVirtualAddress, 53)
	resolved, err := acl.ResolveAndAuthorize(t.Context(), virtual)
	if err != nil {
		t.Fatalf("virtual DNS target rejected: %v", err)
	}
	if len(resolved) != 2 || resolved[0].IP() != upstreams[0] || resolved[1].IP() != upstreams[1] {
		t.Fatalf("virtual DNS target resolved to %v", resolved)
	}

	for _, target := range []conn.Addr{
		conn.AddrFromIPAndPort(nodeDNSVirtualAddress, 443),
		conn.AddrFromIPAndPort(upstreams[0], 53),
	} {
		if _, err := acl.ResolveAndAuthorize(t.Context(), target); !errors.Is(err, router.ErrRejected) {
			t.Fatalf("non-virtual target %v error = %v, want ErrRejected", target, err)
		}
	}

	wantSource := netip.AddrPortFrom(nodeDNSVirtualAddress, 53)
	if got, ok := acl.ResponseSourceRewrite(virtual, resolved[0]); !ok || got != wantSource {
		t.Fatalf("DNS response rewrite = %v, %v, want %v, true", got, ok, wantSource)
	}
	ordinary := conn.AddrFromIPAndPort(netip.MustParseAddr("1.1.1.1"), 53)
	if got, ok := acl.ResponseSourceRewrite(ordinary, ordinary); ok || got.IsValid() {
		t.Fatalf("ordinary DNS unexpectedly received response rewrite %v, %v", got, ok)
	}
}

func TestOutboundACLRejectsVirtualDNSWithoutSystemResolver(t *testing.T) {
	acl := newTestOutboundACL(t, &staticIPResolver{})
	target := conn.AddrFromIPAndPort(nodeDNSVirtualAddress, 53)
	if _, err := acl.ResolveAndAuthorize(t.Context(), target); !errors.Is(err, router.ErrRejected) {
		t.Fatalf("virtual DNS without upstream error = %v, want ErrRejected", err)
	}
}

func TestOutboundACLProtectsControlPlaneLocalAndInjectedTargets(t *testing.T) {
	resolver := &staticIPResolver{answers: map[string][][]netip.Addr{
		"allowed.example": {{netip.MustParseAddr("8.8.4.4")}},
		"private.example": {{netip.MustParseAddr("10.1.2.3")}},
		"local.example":   {{netip.MustParseAddr("93.184.216.34")}},
	}}
	local := &net.IPNet{IP: net.ParseIP("93.184.216.34"), Mask: net.CIDRMask(32, 32)}
	acl, err := newOutboundACLWithDependencies(
		"https://Panel.Example./api/v1",
		[]netip.Prefix{netip.MustParsePrefix("8.8.8.0/24")},
		resolver,
		func() ([]net.Addr, error) { return []net.Addr{local}, nil },
	)
	if err != nil {
		t.Fatal(err)
	}

	for _, target := range []conn.Addr{
		conn.MustAddrFromDomainPort("PANEL.EXAMPLE", 443),
		conn.MustAddrFromDomainPort("panel.example.", 443),
		conn.MustAddrFromDomainPort("private.example", 443),
		conn.MustAddrFromDomainPort("local.example", 443),
		conn.AddrFromIPAndPort(netip.MustParseAddr("8.8.8.8"), 53),
		conn.AddrFromIPAndPort(netip.MustParseAddr("93.184.216.34"), 443),
	} {
		if _, err := acl.ResolveAndAuthorize(t.Context(), target); !errors.Is(err, router.ErrRejected) {
			t.Fatalf("target %v error = %v, want ErrRejected", target, err)
		}
	}

	resolved, err := acl.ResolveAndAuthorize(t.Context(), conn.MustAddrFromDomainPort("allowed.example", 443))
	if err != nil {
		t.Fatalf("allowed domain rejected: %v", err)
	}
	if len(resolved) != 1 || !resolved[0].IsIP() || resolved[0].IP() != netip.MustParseAddr("8.8.4.4") {
		t.Fatalf("allowed domain resolved to %v", resolved)
	}
}

func TestOutboundACLProtectsLiteralControlPlane(t *testing.T) {
	acl, err := newOutboundACLWithDependencies(
		"https://8.8.8.8/api/v1",
		nil,
		&staticIPResolver{},
		emptyInterfaceAddrs,
	)
	if err != nil {
		t.Fatal(err)
	}
	_, err = acl.ResolveAndAuthorize(t.Context(), conn.AddrFromIPAndPort(netip.MustParseAddr("8.8.8.8"), 443))
	if !errors.Is(err, router.ErrRejected) {
		t.Fatalf("literal control-plane error = %v, want ErrRejected", err)
	}
}

func TestOutboundACLBlocksExactControlHostWithoutBlockingSharedAnycastIP(t *testing.T) {
	sharedAnycast := netip.MustParseAddr("104.16.0.1")
	resolver := &staticIPResolver{answers: map[string][][]netip.Addr{
		"unrelated.example": {{sharedAnycast}},
	}}
	acl := newTestOutboundACL(t, resolver)

	if _, err := acl.ResolveAndAuthorize(t.Context(), conn.MustAddrFromDomainPort("PANEL.EXAMPLE.", 443)); !errors.Is(err, router.ErrRejected) {
		t.Fatalf("exact control hostname error = %v, want ErrRejected", err)
	}
	candidates, err := acl.ResolveAndAuthorize(t.Context(), conn.MustAddrFromDomainPort("unrelated.example", 443))
	if err != nil || len(candidates) != 1 || candidates[0].IP() != sharedAnycast {
		t.Fatalf("unrelated shared-Anycast target = %v, %v", candidates, err)
	}
}

func TestOutboundACLRequiresDedicatedPanelOriginInProtectedPrefixes(t *testing.T) {
	dedicatedOrigin := netip.MustParseAddr("93.184.216.34")
	resolver := &staticIPResolver{answers: map[string][][]netip.Addr{
		"origin.example": {{dedicatedOrigin}},
	}}
	acl := newTestOutboundACL(t, resolver, netip.PrefixFrom(dedicatedOrigin, 32))

	if _, err := acl.ResolveAndAuthorize(t.Context(), conn.MustAddrFromDomainPort("origin.example", 443)); !errors.Is(err, router.ErrRejected) {
		t.Fatalf("dedicated Panel origin error = %v, want ErrRejected", err)
	}
}

func TestOutboundACLPinsEachCheckedDNSAnswer(t *testing.T) {
	now := time.Unix(1_000, 0)
	resolver := &staticIPResolver{answers: map[string][][]netip.Addr{
		"rebind.example": {
			{netip.MustParseAddr("8.8.8.8")},
			{netip.MustParseAddr("127.0.0.1")},
		},
	}}
	acl := newTestOutboundACL(t, resolver)
	acl.now = func() time.Time { return now }
	target := conn.MustAddrFromDomainPort("rebind.example", 443)

	first, err := acl.ResolveAndAuthorize(t.Context(), target)
	if err != nil {
		t.Fatalf("first lookup: %v", err)
	}
	if len(first) != 1 || !first[0].IsIP() || first[0].IP() != netip.MustParseAddr("8.8.8.8") {
		t.Fatalf("first lookup was not pinned to checked IP: %v", first)
	}
	second, err := acl.ResolveAndAuthorize(t.Context(), target)
	if err != nil || len(second) != 1 || second[0].IP() != netip.MustParseAddr("8.8.8.8") {
		t.Fatalf("positive cache did not pin first answer: %v, %v", second, err)
	}
	if resolver.calls["rebind.example"] != 1 {
		t.Fatalf("resolver calls within positive TTL = %d, want 1", resolver.calls["rebind.example"])
	}

	now = now.Add(outboundDNSPositiveTTL + time.Nanosecond)
	if _, err := acl.ResolveAndAuthorize(t.Context(), target); !errors.Is(err, router.ErrRejected) {
		t.Fatalf("rebound private answer after TTL error = %v, want ErrRejected", err)
	}
	if resolver.calls["rebind.example"] != 2 {
		t.Fatalf("resolver calls after positive TTL = %d, want 2", resolver.calls["rebind.example"])
	}
}

func TestOutboundACLChecksAllDNSAnswersAndKeepsAllowedOrder(t *testing.T) {
	resolver := &staticIPResolver{answers: map[string][][]netip.Addr{
		"multi.example": {{
			netip.MustParseAddr("10.0.0.1"),
			netip.MustParseAddr("8.8.8.8"),
			netip.MustParseAddr("8.8.8.8"),
			netip.MustParseAddr("1.1.1.1"),
		}},
	}}
	acl := newTestOutboundACL(t, resolver)
	candidates, err := acl.ResolveAndAuthorize(t.Context(), conn.MustAddrFromDomainPort("multi.example", 443))
	if err != nil {
		t.Fatalf("mixed DNS answers rejected: %v", err)
	}
	if len(candidates) != 2 || candidates[0].IP() != netip.MustParseAddr("8.8.8.8") || candidates[1].IP() != netip.MustParseAddr("1.1.1.1") {
		t.Fatalf("authorized candidates = %v", candidates)
	}
}

func TestOutboundACLRefreshesPinnedAllowedCandidateAfterTTL(t *testing.T) {
	now := time.Unix(1_500, 0)
	resolver := &staticIPResolver{answers: map[string][][]netip.Addr{
		"rotate.example": {
			{netip.MustParseAddr("8.8.8.8"), netip.MustParseAddr("1.1.1.1")},
			{netip.MustParseAddr("9.9.9.9"), netip.MustParseAddr("1.0.0.1")},
		},
	}}
	acl := newTestOutboundACL(t, resolver)
	acl.now = func() time.Time { return now }
	target := conn.MustAddrFromDomainPort("rotate.example", 443)

	first, err := acl.ResolveAndAuthorize(t.Context(), target)
	if err != nil || len(first) != 2 || first[0].IP() != netip.MustParseAddr("8.8.8.8") {
		t.Fatalf("first cache generation = %v, %v", first, err)
	}
	now = now.Add(outboundDNSPositiveTTL + time.Nanosecond)
	second, err := acl.ResolveAndAuthorize(t.Context(), target)
	if err != nil || len(second) != 2 || second[0].IP() != netip.MustParseAddr("9.9.9.9") {
		t.Fatalf("refreshed cache generation = %v, %v", second, err)
	}
}

type resolverFunc func(context.Context, string, string) ([]netip.Addr, error)

func (f resolverFunc) LookupNetIP(ctx context.Context, network, host string) ([]netip.Addr, error) {
	return f(ctx, network, host)
}

func TestOutboundACLCanonicalizesAndNegativeCachesDNSFailures(t *testing.T) {
	now := time.Unix(2_000, 0)
	var calls atomic.Int64
	var badResolverInput atomic.Bool
	acl := newTestOutboundACL(t, resolverFunc(func(_ context.Context, network, host string) ([]netip.Addr, error) {
		if network != "ip4" || host != "missing.example" {
			badResolverInput.Store(true)
			return nil, errors.New("unexpected resolver input")
		}
		calls.Add(1)
		return nil, errors.New("host-specific resolver detail must not escape")
	}))
	acl.now = func() time.Time { return now }

	for _, domain := range []string{"Missing.Example.", "missing.example", "MISSING.EXAMPLE.."} {
		_, err := acl.ResolveAndAuthorize(t.Context(), conn.MustAddrFromDomainPort(domain, 53))
		if !errors.Is(err, service.ErrOutboundPolicyResolution) {
			t.Fatalf("domain %q error = %v, want aggregate resolution error", domain, err)
		}
		if strings.Contains(err.Error(), "host-specific") || strings.Contains(err.Error(), domain) {
			t.Fatalf("resolver detail leaked through policy error: %v", err)
		}
	}
	if calls.Load() != 1 {
		t.Fatalf("resolver calls within negative TTL = %d, want 1", calls.Load())
	}
	if badResolverInput.Load() {
		t.Fatal("resolver did not receive the canonical hostname and ip4 network")
	}

	now = now.Add(outboundDNSNegativeTTL + time.Nanosecond)
	_, _ = acl.ResolveAndAuthorize(t.Context(), conn.MustAddrFromDomainPort("missing.example", 53))
	if calls.Load() != 2 {
		t.Fatalf("resolver calls after negative TTL = %d, want 2", calls.Load())
	}
}

func TestOutboundACLDeduplicatesConcurrentCanonicalLookups(t *testing.T) {
	var calls atomic.Int64
	var badResolverHost atomic.Bool
	started := make(chan struct{})
	release := make(chan struct{})
	acl := newTestOutboundACL(t, resolverFunc(func(ctx context.Context, _, host string) ([]netip.Addr, error) {
		if host != "singleflight.example" {
			badResolverHost.Store(true)
			return nil, errors.New("unexpected resolver host")
		}
		if calls.Add(1) == 1 {
			close(started)
		}
		select {
		case <-release:
			return []netip.Addr{netip.MustParseAddr("8.8.8.8")}, nil
		case <-ctx.Done():
			return nil, ctx.Err()
		}
	}))

	const workers = 32
	errs := make(chan error, workers)
	var wg sync.WaitGroup
	wg.Add(workers)
	for i := 0; i < workers; i++ {
		go func(index int) {
			defer wg.Done()
			domain := "singleflight.example"
			if index%2 == 0 {
				domain = "SINGLEFLIGHT.EXAMPLE."
			}
			_, err := acl.ResolveAndAuthorize(t.Context(), conn.MustAddrFromDomainPort(domain, 443))
			errs <- err
		}(i)
	}
	<-started
	close(release)
	wg.Wait()
	close(errs)
	for err := range errs {
		if err != nil {
			t.Fatalf("concurrent lookup failed: %v", err)
		}
	}
	if calls.Load() != 1 {
		t.Fatalf("concurrent resolver calls = %d, want 1", calls.Load())
	}
	if badResolverHost.Load() {
		t.Fatal("concurrent lookup did not use the canonical hostname")
	}
}

func TestOutboundACLDNSCacheIsBounded(t *testing.T) {
	acl := newTestOutboundACL(t, resolverFunc(func(_ context.Context, _, _ string) ([]netip.Addr, error) {
		return []netip.Addr{netip.MustParseAddr("8.8.8.8")}, nil
	}))
	for index := 0; index < outboundDNSCacheMax+64; index++ {
		domain := fmt.Sprintf("host-%d.example", index)
		if _, err := acl.ResolveAndAuthorize(t.Context(), conn.MustAddrFromDomainPort(domain, 443)); err != nil {
			t.Fatalf("resolve %s: %v", domain, err)
		}
	}
	acl.dnsMu.Lock()
	cacheSize := len(acl.dnsCache)
	acl.dnsMu.Unlock()
	if cacheSize > outboundDNSCacheMax {
		t.Fatalf("DNS cache size = %d, max %d", cacheSize, outboundDNSCacheMax)
	}
}

func TestOutboundACLRecognizesEmbeddedIPv4(t *testing.T) {
	private := netip.MustParseAddr("10.1.2.3")
	mapped := netip.MustParseAddr("::ffff:10.1.2.3")
	if got, ok := embeddedIPv4(mapped); !ok || got != private {
		t.Fatalf("mapped extraction = %v, %v", got, ok)
	}

	metadata := netip.MustParseAddr("169.254.169.254")
	wkp := netip.MustParseAddr("64:ff9b::a9fe:a9fe")
	if got, ok := embeddedIPv4(wkp); !ok || got != metadata {
		t.Fatalf("well-known NAT64 extraction = %v, %v", got, ok)
	}

	b := localUseNAT64Prefix.Addr().As16()
	metadataBytes := metadata.As4()
	b[6], b[7], b[9], b[10] = metadataBytes[0], metadataBytes[1], metadataBytes[2], metadataBytes[3]
	localUse := netip.AddrFrom16(b)
	if got, ok := embeddedIPv4(localUse); !ok || got != metadata {
		t.Fatalf("local-use NAT64 extraction = %v, %v", got, ok)
	}
}

func TestOutboundACLInterfaceEnumerationFailureIsFatal(t *testing.T) {
	_, err := newOutboundACLWithDependencies(
		"https://panel.example",
		nil,
		&staticIPResolver{},
		func() ([]net.Addr, error) { return nil, errors.New("test failure") },
	)
	if err == nil {
		t.Fatal("interface enumeration failure was accepted")
	}
}
