name: Test with gotip

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: stable

      - name: Install gotip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download

      - name: Build
        run: |
          gotip build -v -trimpath -ldflags '-s -w' ./cmd/shadowsocks-go
          gotip build -v -trimpath -ldflags '-s -w' ./cmd/shadowsocks-go-domain-set-converter
          gotip build -v -trimpath -ldflags '-s -w' ./cmd/sstest

      - name: Test
        run: gotip test -v ./...

      - name: Upload Binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: shadowsocks-go-${{ github.sha }}-linux-${{ runner.arch }}
          path: |
            shadowsocks-go
            shadowsocks-go-domain-set-converter
            sstest
